ALTER TYPE "UserRole" ADD VALUE 'FINANCIAL_MANAGER';
ALTER TYPE "UserRole" ADD VALUE 'MARKETING';
ALTER TYPE "UserRole" ADD VALUE 'CLEANING_SUPERVISOR';
ALTER TYPE "UserRole" ADD VALUE 'SHAREHOLDER';
